# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = pd.read_csv("/content/house prediction.csv")

df.head()

le = LabelEncoder()

df["area_type"] = le.fit_transform(df["area_type"])
df["availability"] = le.fit_transform(df["availability"])
df["location"] = le.fit_transform(df["location"])

X = df.drop("price", axis=1)
y = df["price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=55
)

model = DecisionTreeRegressor(random_state=55)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("R2 Score :", r2_score(y_test, y_pred))

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

plt.figure(figsize=(20,10))
plot_tree(
    model,
    feature_names=X.columns,
    filled=True,
    rounded=True,
    fontsize=8
)
plt.show()

new_house = [[2, 1, 10, 3, 1500, 2, 2]]

prediction = model.predict(new_house)

print("Predicted House Price:", prediction[0], "Lakhs")